### PR TITLE
feat: implement setUpdateCallback(Consumer func) for Watcher interface

### PR DESCRIPTION
**Pull request by seriouszyx**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx plz setup semantic-release first

**Comment by seriouszyx** [comment]
@hsluoyz  need the following repo secrets, I don't have permission to add.

- GPG_KEY_NAME
- GPG_PASSPHRASE
- GPG_PRIVATE_KEY
- GITHUB_TOKEN
- OSSRH_JIRA_PASSWORD
- OSSRH_JIRA_USERNAME

**Comment by hsluoyz** [comment]
@tangyang9464 tell him how to do it

**Comment by tangyang9464** [comment]
> @tangyang9464 tell him how to do it

@hsluoyz sry, I don't konw how to do it. I can only add secrets in my own repository.

**Comment by hsluoyz** [comment]
@seriouszyx you can use these:

image

**Pull request merged**
